# Generated by Django 4.2.9 on 2024-02-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("feedback", "0002_alter_sbi_feedback_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DESC_Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("describe", models.TextField()),
                ("explain", models.TextField()),
                ("specify", models.TextField()),
                ("consequences", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desc_provided_feedback",
                        to="employees.employee",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desc_received_feedback",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
