# Generated by Django 4.2.9 on 2024-02-08 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('feedback', '0003_desc_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc_feedback',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_provided_feedback', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='desc_feedback',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received_feedback', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='sbi_feedback',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_provided_feedback', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='sbi_feedback',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received_feedback', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='GROW_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.TextField()),
                ('reality', models.TextField()),
                ('options', models.TextField()),
                ('will', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_provided_feedback', to='employees.employee')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received_feedback', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
